#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
if ! [ -f ./buildenv ]; then
	echo "Need to source from the buildenv directory" >&2
	return 0
fi

export ZOPEN_ROOT="${PWD}"
export ZOPEN_TYPE="TARBALL"
export ZOPEN_TARBALL_URL="https://github.com/Cyan4973/xxHash/archive/refs/tags/v0.8.1.tar.gz"
export ZOPEN_TARBALL_DEPS="curl gzip make"

export ZOPEN_BOOTSTRAP=skip
export ZOPEN_CONFIGURE=skip

rm -f v0.8.1
ln -s xxHash-0.8.1 v0.8.1
